
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140808 (SVN rev 54)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ST = 29;
  public static final int GTEQ = 32;
  public static final int STR = 10;
  public static final int UMINUS = 50;
  public static final int INTEGER = 48;
  public static final int CONTINUE = 15;
  public static final int INT = 8;
  public static final int LSP = 44;
  public static final int STATIC = 6;
  public static final int NOT = 39;
  public static final int AND = 35;
  public static final int LP = 40;
  public static final int OR = 36;
  public static final int COMMA = 37;
  public static final int CLASS = 4;
  public static final int RP = 41;
  public static final int DIV = 26;
  public static final int EOL = 27;
  public static final int PLUS = 23;
  public static final int QUOTE = 49;
  public static final int IF = 11;
  public static final int THIS = 16;
  public static final int ID = 47;
  public static final int DOT = 38;
  public static final int EOF = 0;
  public static final int BOOLEAN = 9;
  public static final int RETURN = 3;
  public static final int TRUE = 19;
  public static final int NEW = 17;
  public static final int error = 1;
  public static final int MUL = 24;
  public static final int RSP = 45;
  public static final int NULL = 21;
  public static final int EQEQ = 33;
  public static final int MOD = 28;
  public static final int LRP = 42;
  public static final int BREAK = 14;
  public static final int VOID = 7;
  public static final int EQ = 22;
  public static final int ELSE = 12;
  public static final int WHILE = 13;
  public static final int CLASS_ID = 46;
  public static final int EXTENDS = 5;
  public static final int STRING = 2;
  public static final int RRP = 43;
  public static final int FALSE = 20;
  public static final int GT = 31;
  public static final int SUB = 25;
  public static final int LENGTH = 18;
  public static final int STEQ = 30;
  public static final int NOTEQ = 34;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "STRING",
  "RETURN",
  "CLASS",
  "EXTENDS",
  "STATIC",
  "VOID",
  "INT",
  "BOOLEAN",
  "STR",
  "IF",
  "ELSE",
  "WHILE",
  "BREAK",
  "CONTINUE",
  "THIS",
  "NEW",
  "LENGTH",
  "TRUE",
  "FALSE",
  "NULL",
  "EQ",
  "PLUS",
  "MUL",
  "SUB",
  "DIV",
  "EOL",
  "MOD",
  "ST",
  "STEQ",
  "GT",
  "GTEQ",
  "EQEQ",
  "NOTEQ",
  "AND",
  "OR",
  "COMMA",
  "DOT",
  "NOT",
  "LP",
  "RP",
  "LRP",
  "RRP",
  "LSP",
  "RSP",
  "CLASS_ID",
  "ID",
  "INTEGER",
  "QUOTE",
  "UMINUS"
  };
}

